server:
  port: ${PORT:5000}
security:
  user:
    password: ${EUREKA_PASSWORD:password}

spring:
  profiles: peer
eureka:
  server:
    enable-self-preservation: true
    renewalPercentThreshold: 0.33
  instance:
    hostname: ${EUREKA_HOST:localhost}
    secure-port-enabled: true
    nonSecurePort: 80
    securePort: 443
    statusPageUrl: https://${eureka.hostname}:443/actuator/info
    healthCheckUrl: https://${eureka.hostname}:443/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:443/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

