server:
  port: ${PORT:5000}
security:
  user:
    password: ${EUREKA_PASSWORD:password}

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: ${EUREKA_HOST:localhost}
    secure-port-enabled: true
    nonSecurePort: 80
    securePort: 443
    statusPageUrl: https://${eureka.hostname}:443/actuator/info
    healthCheckUrl: https://${eureka.hostname}:443/actuator/health
    secureHealthCheckUrl: https://${eureka.hostname}:443/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
